[package]
name = "stoat"
version = "0.1.0"
edition = "2021"
description = "A exploratory text editor."
readme = "../README.md"
authors = ["Lee Olayvar <leegit@fastmail.com>"]
license-file = "../LICENSE"

[dependencies]
